### ISSUE TITLE
为什么没有原始SiamFC_AlexNet的结果呢?SiamFC作为孪生网络的代表作应当被考虑在论文中

### ISSUE THREAD

**Issue by xiaoxianya** [vision4robotics/SiameseTracking4UAV#6]

**Comment by L-KH97** [comment]
Thanks for your question
1) As a pioneer of the Siamese tracker, this work notices the far-reaching impact of SiamFC, and it has been reviewed in detail in our article, which you can refer to in the provided link. However, since the official Python code does not release,  for fairness, this work evaluates trackers with open source code.
2) The purpose of this work is to provide a Python code library for usage by the tracking community as well as practical UAV-based tracking deployments.
3) This work includes as many leading-edge and representative Siamese trackers as possible for evaluation. The results could be found in the 'results' folder or in our article.

感谢您的问题
1）作为 Siamese 跟踪器的先驱，这项工作注意到了 SiamFC 的深远影响，并在我们的文章中进行了详细回顾，您可以在提供的链接中参考。但是，由于官方 Python 代码没有发布，为了公平起见，这项工作使用开源代码评估跟踪器。
2）这项工作的目的是提供一个 Python 代码库，供跟踪社区以及实际的无人机跟踪部署使用。
3）这项工作涵盖尽可能多的前沿和有代表性的Siamese追踪器进行评估。结果可以在“results”文件夹或我们的文章中查阅到。
